"""create pull requests table

Revision ID: 1df7cbb67bee
Revises: 9874857856d8
Create Date: 2026-07-11 22:11:48.337339

"""
from typing import Sequence, Union

from alembic import op  # pyright: ignore[reportMissingImports]
import sqlalchemy as sa  # pyright: ignore[reportMissingImports]


# revision identifiers, used by Alembic.
revision: str = '1df7cbb67bee'
down_revision: Union[str, Sequence[str], None] = '9874857856d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
