"""store github refresh token

Revision ID: 1fc16536c201
Revises: 73d6acc22ca5
Create Date: 2026-10-06 02:24:12.462947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc16536c201'
down_revision: Union[str, Sequence[str], None] = '73d6acc22ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_access_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('github_refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_refresh_token_expires_at')
    op.drop_column('users', 'github_access_token_expires_at')
    op.drop_column('users', 'github_refresh_token')
    # ### end Alembic commands ###
