"""cascade deletes from repositories

Revision ID: 73d6acc22ca5
Revises: 76ce37e78f9f
Create Date: 2026-09-28 04:04:17.207413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d6acc22ca5'
down_revision: Union[str, Sequence[str], None] = '76ce37e78f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pull_request_files_pull_request_id_fkey'), 'pull_request_files', type_='foreignkey')
    op.create_foreign_key(None, 'pull_request_files', 'pull_requests', ['pull_request_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pull_requests_repository_id_fkey'), 'pull_requests', type_='foreignkey')
    op.create_foreign_key(None, 'pull_requests', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('review_findings_pr_file_id_fkey'), 'review_findings', type_='foreignkey')
    op.drop_constraint(op.f('review_findings_review_job_id_fkey'), 'review_findings', type_='foreignkey')
    op.create_foreign_key(None, 'review_findings', 'review_jobs', ['review_job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_findings', 'pull_request_files', ['pr_file_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('review_jobs_pull_request_id_fkey'), 'review_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'review_jobs', 'pull_requests', ['pull_request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('review_jobs_pull_request_id_fkey'), 'review_jobs', 'pull_requests', ['pull_request_id'], ['id'])
    op.drop_constraint(None, 'review_findings', type_='foreignkey')
    op.drop_constraint(None, 'review_findings', type_='foreignkey')
    op.create_foreign_key(op.f('review_findings_review_job_id_fkey'), 'review_findings', 'review_jobs', ['review_job_id'], ['id'])
    op.create_foreign_key(op.f('review_findings_pr_file_id_fkey'), 'review_findings', 'pull_request_files', ['pr_file_id'], ['id'])
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.create_foreign_key(op.f('pull_requests_repository_id_fkey'), 'pull_requests', 'repositories', ['repository_id'], ['id'])
    op.drop_constraint(None, 'pull_request_files', type_='foreignkey')
    op.create_foreign_key(op.f('pull_request_files_pull_request_id_fkey'), 'pull_request_files', 'pull_requests', ['pull_request_id'], ['id'])
    # ### end Alembic commands ###
