"""add github_webhook_event

Revision ID: 76ce37e78f9f
Revises: da4f890f76ba
Create Date: 2026-08-28 23:47:58.696224

"""
from typing import Sequence, Union

from alembic import op  # pyright: ignore[reportMissingImports]
import sqlalchemy as sa  # pyright: ignore[reportMissingImports]


# revision identifiers, used by Alembic.
revision: str = '76ce37e78f9f'
down_revision: Union[str, Sequence[str], None] = 'da4f890f76ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
