"""fix repo uniqueness per user

Revision ID: 9874857856d8
Revises: 79dce57a824a
Create Date: 2026-07-08 02:47:58.253196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9874857856d8'
down_revision: Union[str, Sequence[str], None] = '79dce57a824a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_repositories_github_repo_id'), 'repositories', type_='unique')
    op.create_unique_constraint('uq_repositories_user_repo', 'repositories', ['github_repo_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repositories_user_repo', 'repositories', type_='unique')
    op.create_unique_constraint(op.f('uq_repositories_github_repo_id'), 'repositories', ['github_repo_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
