"""create pull request files table

Revision ID: b1ec83946097
Revises: b64a9fc20a64
Create Date: 2026-07-12 21:29:00.315404

"""
from typing import Sequence, Union

from alembic import op  # pyright: ignore[reportMissingImports]
import sqlalchemy as sa  # pyright: ignore[reportMissingImports]


# revision identifiers, used by Alembic.
revision: str = 'b1ec83946097'
down_revision: Union[str, Sequence[str], None] = 'b64a9fc20a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('previous_filename', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sha', sa.String(length=255), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changes', sa.Integer(), nullable=False),
    sa.Column('blob_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_url', sa.String(length=1000), nullable=True),
    sa.Column('contents_url', sa.String(length=1000), nullable=True),
    sa.Column('patch', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'filename', name='uq_pull_request_files_pr_filename')
    )
    op.create_index(op.f('ix_pull_request_files_pull_request_id'), 'pull_request_files', ['pull_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_request_files_pull_request_id'), table_name='pull_request_files')
    op.drop_table('pull_request_files')
    # ### end Alembic commands ###
