"""create pull requests table

Revision ID: b64a9fc20a64
Revises: 1df7cbb67bee
Create Date: 2026-07-11 22:15:35.034332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64a9fc20a64'
down_revision: Union[str, Sequence[str], None] = '1df7cbb67bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('head_branch', sa.String(length=255), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('github_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_pr_id', name='uq_pull_request_repo_github_pr')
    )
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
