"""create review findings table

Revision ID: da4f890f76ba
Revises: 488a347fe17b
Create Date: 2026-07-21 23:17:06.059309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4f890f76ba'
down_revision: Union[str, Sequence[str], None] = '488a347fe17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_job_id', sa.Integer(), nullable=False),
    sa.Column('pr_file_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='review_finding_severity'), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_file_id'], ['pull_request_files.id'], ),
    sa.ForeignKeyConstraint(['review_job_id'], ['review_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_pr_file_id'), 'review_findings', ['pr_file_id'], unique=False)
    op.create_index(op.f('ix_review_findings_review_job_id'), 'review_findings', ['review_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_findings_review_job_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_pr_file_id'), table_name='review_findings')
    op.drop_table('review_findings')
    # ### end Alembic commands ###
