"""add github token fields to user

Revision ID: db9c6a93cc2b
Revises: 75f815f23d58
Create Date: 2026-07-08 01:27:37.738094

"""
from typing import Sequence, Union

from alembic import op  # pyright: ignore[reportMissingImports]
import sqlalchemy as sa  # pyright: ignore[reportMissingImports]


# revision identifiers, used by Alembic.
revision: str = 'db9c6a93cc2b'
down_revision: Union[str, Sequence[str], None] = '75f815f23d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_token_scope', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_token_scope')
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
